all:
	gcc -Wall -o main1 main1.c -I. -lpthread
	gcc -Wall -o main2 main2.c -I. -lpthread
	gcc -Wall -o main3 main3.c -I. -lpthread
	gcc -Wall -o main4 main4.c -I. -lpthread
	gcc -Wall -o main5 main5.c -I. -lpthread
	gcc -Wall -o mainB mainB.c -I. -lpthread
clean:
	rm main1 main2 main3 main4 main5 mainB
